FROM ubuntu:24.04 as compile
# Install Dependencies
WORKDIR /app
RUN apt update && apt install -y \
  curl \
  ninja-build \
  build-essential \
  libboost-all-dev \
  libprotobuf-dev \
  protobuf-compiler \
  lsb-release \
  wget \
  software-properties-common \
  gnupg \
  ninja-build \
  cmake \
  clang-18 \
  clang-tools-18

# Copy and Cache
WORKDIR /app/file-lock
COPY . /app/file-lock
RUN rm -rf /app/file-lock/build


# Build
WORKDIR /app/file-lock
RUN CXX=clang++-18 cmake -B build -GNinja -DCMAKE_BUILD_TYPE=Release .
WORKDIR /app/file-lock/build
RUN ninja multiprocessing_file_lock_python

FROM scratch as export
COPY --from=compile /app/file-lock/build/file_lock.so /file_lock.so