ARG PYTHON_VERSION
FROM jowillianto/cpp-module-cont as compile
ARG PYTHON_VERSION
RUN add-apt-repository ppa:deadsnakes/ppa
RUN apt update && DEBIAN_FRONTEND=noninteractive apt install -y \
  python${PYTHON_VERSION}-dev \
  python${PYTHON_VERSION}-distutils
RUN python${PYTHON_VERSION} --version
# Copy and Cache
WORKDIR /app/file-lock
COPY ./lib/file-lock /app/file-lock
RUN rm -rf /app/file-lock/build

# Build
WORKDIR /app/file-lock
RUN CXX=clang++-18 cmake \
  -B build \
  -GNinja \
  -DPython3_EXECUTABLE=/usr/bin/python${PYTHON_VERSION} \
  -DPYBIND11_PYTHON_VERSION=${PYTHON_VERSION} \
  -DCMAKE_BUILD_TYPE=Release .d
WORKDIR /app/file-lock/build

# Build Python
RUN ninja multiprocessing_file_lock_python

FROM python:${PYTHON_VERSION}-slim as test
COPY ./setup.py /app/setup.py
COPY ./module_api /app/module_api
COPY ./MANIFEST.in /app/MANIFEST.in
COPY --from=compile /app/file-lock/build/file_lock.so /app/module_api/API/file_lock.so
WORKDIR /app
RUN pip install .
WORKDIR /
RUN python3 -m unittest module_api.API.lock.tests
RUN python3 -m unittest module_api.API.patterns.tests
RUN python3 -m unittest module_api.API.display.tests
RUN python3 -m unittest module_api.API.timer.tests
RUN python3 -m unittest module_api.API.runnable.tests
RUN python3 -m unittest module_api.API.error.tests

RUN pip install wheel
WORKDIR /app
RUN python3 setup.py bdist_wheel

FROM scratch AS export
COPY --from=test /app/dist /