class WsgiErrorCode:
    UNKNOW_ERROR = 0
    PROCESS_WAS_KILLED = 1
    FAIL_RUNNING = 2
    COMMAND_NOT_FOUND = 3
    INVALID_PAYLOAD = 4
    INVALID_COMMAND = 5
    INVALID_LOCK_PATH = 6
    INVALID_REQUEST_METHOD = 7
    NETWORK_ERROR = 8